trigger:
- main

pool:
  name: Default  # Replace with your self-hosted agent pool name if different

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true